version: '3.8'

services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /workspace
    volumes:
      - ./:/workspace:cached
      - node_modules:/workspace/node_modules

volumes:
  node_modules:
